const express = require('express')
const router = express.Router()
const PetsControllers = require('../Controllers/petsControllers')
const {updload,imageURL} = require('../Middleware/imagesMiddleware')
const {validateBody} = require('../Middleware/validateBody.js')
const {addPetsSchema} = require('../Schemas/addPetsSchema')
const {filterQuery} = require('../Middleware/petsMiddleware')
const {searchSchema} = require('../Schemas/searchSchema')


router.get('/color',PetsControllers.setColorOfPets)
router.get('/type',PetsControllers.setTypeOfPets)
router.get('/breed',PetsControllers.setBreedOfPets)
router.post('/addpet',updload.single('imagePet'),imageURL,validateBody(addPetsSchema),PetsControllers.addPets)
router.get('/pet/:id_pet',PetsControllers.getPetById)
router.get('/user/:id_user',PetsControllers.getPetByUserId)
router.post('/operations',PetsControllers.operations)
router.put('/adopt',PetsControllers.adoptPet)
router.put('/foster',PetsControllers.fosterPet)
router.put('/return',PetsControllers.returnPet)
router.post('/savepets',PetsControllers.savePet)
router.delete('/savepets/:id_user/:id_pet',PetsControllers.unsavePet)
router.get('/savedpets/:id_user',PetsControllers.getSavedPets)
router.get('/search',validateBody(searchSchema),filterQuery,PetsControllers.searchPets)
router.get('/viewpets',PetsControllers.getPetsView)
router.get('/viewhistoricaloperations',PetsControllers.getHistoricalOperationsView)
router.delete('/pet/:id_pet',PetsControllers.deletePet)
router.get('/petsbyuser/:id_user',PetsControllers.getPetsByUser)

module.exports = router
